name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create Terraform Plan Directory
        run: mkdir -p terraform-plan

      - name: Show files in current directory
        run: ls -R

      - name: Show files in terraform-plan directory
        run: ls -R terraform-plan

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Refresh
        run: terraform refresh

      - name: Terraform Plan
        run: terraform plan -out=terraform-plan/tfplan

  manual-approval:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ secrets.MY_TOKEN }}
          approvers: PraveenKumar-Kasoju
          minimum-approvals: 1
          issue-title: "Terraform apply approval"
          issue-body: "Please approve or deny the deployment of Terraform."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  terraform-apply:
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Show files in terraform-plan directory
        run: terraform plan -out=tfplan .

      - name: Copy Terraform Plan
        run: cp terraform-plan/tfplan .

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
