name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Manual Approval
        run: echo "Waiting for manual approval"

      - name: Set Manual Approval Status
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/check-suites/:check_suite_id/rerequest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
