name: GitHub App Workflow

on:
  check_suite:
    types:
      - requested

jobs:
  manual-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check Manual Approval
        run: echo "approved" >> $GITHUB_ENV
